- hosts: localhost
  tasks:

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install Prerequisites
    import_role:
      name: prerequisites

  - name: Elk_Stack Repo
    import_role:
      name: elk_stack

  - name: Install ElasticSearch
    import_role:
      name: elasticsearch
  
  - name: Install Kibana
    import_role:
      name: kibana

  - name: Install Logstash
    import_role:
      name: logstash

  - name: Install Filebeat
    import_role:
      name: filebeat
